[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.associations"
version = "3.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina", "associations", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.associations"

[build-options]
observabilityIncluded = true
